from __future__ import annotations

from .script_generation_config import ScriptGenerationConfig
from core.shaping.shaped_action_sequence import ShapedActionSequence


def render_header_comments(
    shaped: ShapedActionSequence,
    *,
    config: ScriptGenerationConfig,
) -> list[str]:
    if not config.include_header_comments:
        return []

    lines = [
        "# Generated by ActionShellScript",
    ]

    if config.include_source_summary:
        lines.append(f"# Source session: {shaped.source_session_id}")
        lines.append(f"# Shaped action count: {shaped.action_count()}")

    return lines
