from __future__ import annotations

from core.scripting.generation.header_comment_renderer import render_header_comments
from core.scripting.generation.script_generation_config import ScriptGenerationConfig
from core.shaping.shaped_action_sequence import ShapedActionSequence


def test_header_comments_include_source_summary_by_default() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-4",
        source_interpreted_event_count=3,
        actions=[{"type": "text", "text": "hi"}],
    )

    lines = render_header_comments(shaped, config=ScriptGenerationConfig())

    assert lines == [
        "# Generated by ActionShellScript",
        "# Source session: session-4",
        "# Shaped action count: 1",
    ]


def test_header_comments_can_be_disabled_independently_of_summary() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-4",
        source_interpreted_event_count=0,
        actions=[],
    )

    lines = render_header_comments(
        shaped,
        config=ScriptGenerationConfig(
            include_header_comments=False,
            include_source_summary=True,
        ),
    )

    assert lines == []


def test_header_comments_can_omit_source_summary() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-4",
        source_interpreted_event_count=2,
        actions=[{"type": "mouse_move", "x": 1, "y": 2}],
    )

    lines = render_header_comments(
        shaped,
        config=ScriptGenerationConfig(include_source_summary=False),
    )

    assert lines == ["# Generated by ActionShellScript"]
