from __future__ import annotations

import json

from apps.cli.generate_command import build_parser, run


def test_generate_command_parser_defaults_to_session_json() -> None:
    args = build_parser().parse_args([])

    assert args.session_path == r".\session.json"


def test_generate_command_parser_accepts_generation_flags() -> None:
    args = build_parser().parse_args(
        [
            "session.json",
            "--no-header-comments",
            "--emit-unsupported-comments",
            "--line-ending",
            "crlf",
        ]
    )

    assert args.no_header_comments is True
    assert args.emit_unsupported_comments is True
    assert args.line_ending == "crlf"


def test_generate_command_parser_accepts_force_flag() -> None:
    args = build_parser().parse_args(["session.json", "--force"])

    assert args.force is True


def test_generate_command_runs_end_to_end_and_can_write_output(tmp_path, capsys) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "generated.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-11",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )

    exit_code = run([str(session_path), "--output", str(output_path)])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-11" in captured.out
    assert "Interpreted event count: 1" in captured.out
    assert "Shaped action count    : 1" in captured.out
    assert "Generated line count   : 5" in captured.out
    assert 'Hotkey("ctrl", "c")' in captured.out
    assert output_path.read_text(encoding="utf-8") == (
        "# Generated by ActionShellScript\n"
        "# Source session: session-11\n"
        "# Shaped action count: 1\n"
        "\n"
        'Hotkey("ctrl", "c")\n'
    )


def test_generate_command_uses_default_session_json_when_input_is_omitted(
    tmp_path,
    capsys,
    monkeypatch,
) -> None:
    session_path = tmp_path / "session.json"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-default",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)

    exit_code = run(["--output", str(tmp_path / "generated.ass")])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-default" in captured.out


def test_generate_command_refuses_to_overwrite_existing_output_without_force(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "generated.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-12",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    output_path.write_text("# existing\n", encoding="utf-8")

    exit_code = run([str(session_path), "--output", str(output_path)])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "Refusing to overwrite" in captured.err
    assert output_path.read_text(encoding="utf-8") == "# existing\n"


def test_generate_command_overwrites_existing_output_with_force(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "generated.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-13",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    output_path.write_text("# existing\n", encoding="utf-8")

    exit_code = run([str(session_path), "--output", str(output_path), "--force"])
    capsys.readouterr()

    assert exit_code == 0
    assert output_path.read_text(encoding="utf-8") == (
        "# Generated by ActionShellScript\n"
        "# Source session: session-13\n"
        "# Shaped action count: 1\n"
        "\n"
        'Hotkey("ctrl", "c")\n'
    )
