from __future__ import annotations

from copy import deepcopy

from core.scripting.generation.script_generation_config import ScriptGenerationConfig
from core.scripting.generation.script_generation_pipeline import ScriptGenerationPipeline
from core.shaping.shaped_action_sequence import ShapedActionSequence


def test_script_generation_pipeline_does_not_mutate_shaped_actions() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-5",
        source_interpreted_event_count=2,
        actions=[
            {
                "type": "key_hold",
                "key": "a",
                "timestamp_ms": 100,
                "end_timestamp_ms": 130,
                "duration_ms": 30,
                "source_start_index": 0,
                "source_end_index": 1,
                "source_event_count": 2,
            }
        ],
    )
    original_actions = deepcopy(shaped.actions)

    generated = ScriptGenerationPipeline().generate(shaped)

    assert shaped.actions == original_actions
    assert generated.source_session_id == "session-5"
    assert generated.source_action_count == 1
    assert generated.text.endswith("\n")


def test_script_generation_pipeline_header_flags_affect_output() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-6",
        source_interpreted_event_count=1,
        actions=[{"type": "mouse_move", "x": 3, "y": 4}],
    )

    with_header = ScriptGenerationPipeline().generate(shaped)
    without_header = ScriptGenerationPipeline(
        config=ScriptGenerationConfig(include_header_comments=False)
    ).generate(shaped)

    assert with_header.text.startswith("# Generated by ActionShellScript\n")
    assert without_header.text == "MouseMove(3, 4)\n"


def test_script_generation_pipeline_delay_flag_affects_output() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-7",
        source_interpreted_event_count=2,
        actions=[
            {"type": "delay", "duration_ms": 50},
            {"type": "text", "text": "a"},
        ],
    )

    generated = ScriptGenerationPipeline(
        config=ScriptGenerationConfig(
            include_header_comments=False,
            emit_delays=False,
        )
    ).generate(shaped)

    assert generated.text == 'SendText("a")\n'


def test_script_generation_pipeline_stabilizes_line_endings_and_trailing_newline() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-8",
        source_interpreted_event_count=1,
        actions=[{"type": "mouse_move", "x": 9, "y": 10}],
    )

    generated = ScriptGenerationPipeline(
        config=ScriptGenerationConfig(
            include_header_comments=False,
            line_ending="\r\n",
        )
    ).generate(shaped)

    assert generated.text == "MouseMove(9, 10)\r\n"


def test_script_generation_pipeline_can_return_empty_text_intentionally() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-9",
        source_interpreted_event_count=1,
        actions=[{"type": "delay", "duration_ms": 25}],
    )

    generated = ScriptGenerationPipeline(
        config=ScriptGenerationConfig(
            include_header_comments=False,
            emit_delays=False,
        )
    ).generate(shaped)

    assert generated.text == ""


def test_script_generation_pipeline_emits_supported_contract_mismatches_explicitly() -> None:
    shaped = ShapedActionSequence(
        source_session_id="session-10",
        source_interpreted_event_count=1,
        actions=[{"type": "hotkey", "keys": []}],
    )

    generated = ScriptGenerationPipeline(
        config=ScriptGenerationConfig(include_header_comments=False)
    ).generate(shaped)

    assert generated.text == "# Unsupported shaped action: hotkey\n"
