from __future__ import annotations

import json

from apps.cli.document_command import build_parser, run


def test_document_command_parser_defaults_to_session_json() -> None:
    args = build_parser().parse_args([])

    assert args.session_path == r".\session.json"


def test_document_command_parser_accepts_phase_5_flags() -> None:
    args = build_parser().parse_args(
        [
            "session.json",
            "--show-diagnostics",
            "--show-formatted",
            "--line-ending",
            "crlf",
        ]
    )

    assert args.show_diagnostics is True
    assert args.show_formatted is True
    assert args.line_ending == "crlf"


def test_document_command_parser_accepts_force_flag() -> None:
    args = build_parser().parse_args(["session.json", "--force"])

    assert args.force is True


def test_document_command_parser_accepts_recording_conversion_mode_flag() -> None:
    args = build_parser().parse_args(
        ["session.json", "--recording-conversion-mode", "direct_import"]
    )

    assert args.recording_conversion_mode == "direct_import"


def test_document_command_runs_end_to_end_and_writes_authoritative_text(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "document.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-15",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )

    exit_code = run(
        [
            str(session_path),
            "--output",
            str(output_path),
            "--show-diagnostics",
            "--show-formatted",
        ]
    )
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-15" in captured.out
    assert "Shaped action count    : 1" in captured.out
    assert "Document version       : 1" in captured.out
    assert "Document dirty         : False" in captured.out
    assert "Parse success          : True" in captured.out
    assert "Diagnostics count      : 0" in captured.out
    assert "Authoritative document text:" in captured.out
    assert 'Hotkey("ctrl", "c")' in captured.out
    assert "Diagnostics:\n<none>" in captured.out
    assert "Formatted preview:" in captured.out
    assert output_path.read_text(encoding="utf-8") == (
        "# Recording conversion route: promote_generated\n\n"
        "# Generated by ActionShellScript\n"
        "# Source session: session-15\n"
        "# Shaped action count: 1\n"
        "\n"
        'Hotkey("ctrl", "c")\n'
    )


def test_document_command_uses_default_session_json_when_input_is_omitted(
    tmp_path,
    capsys,
    monkeypatch,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "document.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-default",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    monkeypatch.chdir(tmp_path)

    exit_code = run(["--output", str(output_path)])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-default" in captured.out


def test_document_command_can_directly_import_a_recording_session(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "document.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-18",
                "state": "stopped",
                "started_at_ms": 100,
                "stopped_at_ms": 180,
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )

    exit_code = run(
        [
            str(session_path),
            "--output",
            str(output_path),
            "--recording-conversion-mode",
            "direct_import",
        ]
    )
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-18" in captured.out
    assert "Recording event count  : 4" in captured.out
    assert "Document version       : 1" in captured.out
    assert "Authoritative document text:" in captured.out
    assert "# Imported directly from RecordingSession" in captured.out
    assert "# Session ID: session-18" in captured.out
    assert output_path.read_text(encoding="utf-8").startswith(
        "# Recording conversion route: direct_import\n\n"
        "# Imported directly from RecordingSession\n"
        "# Session ID: session-18\n"
        "# State: stopped\n"
        "# Started at: 100\n"
        "# Stopped at: 180\n"
        "# Event count: 4\n"
    )


def test_document_command_refuses_to_overwrite_existing_document_without_force(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "document.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-16",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    output_path.write_text("# existing\n", encoding="utf-8")

    exit_code = run([str(session_path), "--output", str(output_path)])
    captured = capsys.readouterr()

    assert exit_code == 1
    assert "Refusing to overwrite" in captured.err
    assert output_path.read_text(encoding="utf-8") == "# existing\n"


def test_document_command_overwrites_existing_document_with_force(
    tmp_path,
    capsys,
) -> None:
    session_path = tmp_path / "session.json"
    output_path = tmp_path / "document.ass"
    session_path.write_text(
        json.dumps(
            {
                "session_id": "session-17",
                "state": "stopped",
                "events": [
                    {"type": "key_down", "key": "ctrl", "timestamp_ms": 100},
                    {"type": "key_down", "key": "c", "timestamp_ms": 120},
                    {"type": "key_up", "key": "c", "timestamp_ms": 150},
                    {"type": "key_up", "key": "ctrl", "timestamp_ms": 180},
                ],
            }
        ),
        encoding="utf-8",
    )
    output_path.write_text("# existing\n", encoding="utf-8")

    exit_code = run([str(session_path), "--output", str(output_path), "--force"])
    captured = capsys.readouterr()

    assert exit_code == 0
    assert "Session ID             : session-17" in captured.out
    assert output_path.read_text(encoding="utf-8") == (
        "# Recording conversion route: promote_generated\n\n"
        "# Generated by ActionShellScript\n"
        "# Source session: session-17\n"
        "# Shaped action count: 1\n"
        "\n"
        'Hotkey("ctrl", "c")\n'
    )
