from __future__ import annotations

BUILTIN_FUNCTION_NAMES = frozenset(
    {        
        "abs",
        "appendbytes",
        "appendfile",
        "asc",
        "ascw",
        "base64",
        "arraylength",
        "arrayinsert",
        "arraypop",
        "arraypush",
        "arrayremove",
        "arraycontains",
        "arraycontainsall",
        "arraycount",
        "arrayinitialize",
        "arrayclear",
        "arrayclone",
        "arrayindexof",
        "arraylastindexof",
        "arrayjoin",
        "arrayreverse",
        "arraysort",
        "arrayunique",
        "arraytostring",
        "arrayslice",
        "arrayremoveall",
        "binary",
        "binarylength",
        "binarymid",
        "binarytostring",
        "bitand",
        "bitnot",
        "bitnotunsigned",
        "bitor",
        "bitrotate",
        "bitshift",
        "bitxor",
        "ceiling",
        "chr",
        "chrw",
        "converttimezone",
        "createdir",
        "copydir",
        "copyfile",
        "dateadd",
        "datediff",
        "datepart",
        "dateserial",
        "datetolocalstring",
        "datetostring",
        "datetoutcstring",
        "dayofweek",
        "dayofyear",
        "daysinmonth",
        "deletefile",
        "directorydelete",
        "diagwrite",
        "diagwriteln",
        "movefile",
        "movedir",
        "directoryname",
        "directorylist",
        "enumeratefiles",
        "removedir",
        "direxists",
        "endofday",
        "endofmonth",
        "exp",
        "extensionname",
        "fileexists",
        "filechecksum",
        "filecompare",
        "fileinfo",
        "filename",
        "filelist",
        "filehash",
        "filesize",
        "filetime",
        "walkdir",
        "floor",
        "formatdatetime",
        "formatdatetimeinoffset",
        "frombase64",
        "fromhex",
        "getclassname",
        "getclientrect",
        "getcurrenteventdelay",
        "getcursorpos",
        "getmonitorinfo",
        "getmonitorinfoex",
        "getmousemovespeed",
        "getparent",
        "getwindowlongptr",
        "getwindowplacement",
        "getwindowrect",
        "getwindowtext",
        "hex",
        "hotkey",
        "int",
        "isdate",
        "isiconic",
        "isleapyear",
        "ispathvalid",
        "istime",
        "iswindowenabled",
        "iswindowvisible",
        "iszoomed",
        "keydown",
        "keypress",
        "keytoggle",
        "keyup",
        "localtime",
        "mod",
        "mouseclick",
        "mouseclickdrag",
        "mousedown",
        "mousedrag",
        "mousemove",
        "mouseup",
        "mousewheel",
        "msgbox",
        "nowdate",
        "nowdatetime",
        "nowtime",
        "parsedatetime",
        "parsedatetimeinoffset",
        "pathcombine",
        "pathexists",
        "pathnormalize",
        "pixelgetcolor",
        "pixelsearch",
        "readbytes",
        "readfile",
        "round",
        "stringcontains",
        "regexescape",
        "regexinstr",
        "regexismatch",
        "regexmatch",
        "regexreplace",
        "stringendswith",
        "stringjoin",
        "stringsplit",
        "stringstartswith",
        "sendkeys",
        "sendtext",
        "setcurrenteventdelay",
        "setmousemovespeed",
        "sleep",
        "startofday",
        "startofmonth",
        "startofweek",
        "string",
        "stringcompare",
        "stringinstr",
        "stringisalpha",
        "stringisalphanumeric",
        "stringisascii",
        "stringisdigit",
        "stringisfloat",
        "stringisint",
        "stringislower",
        "stringisspace",
        "stringisupper",
        "stringleft",
        "stringlength",
        "stringmid",
        "stringreplace",
        "stringreverse",
        "stringright",
        "stringtolower",
        "stringtoupper",
        "stringtrimleft",
        "stringtrimright",
        "time",
        "timeserial",
        "timezoneoffset",
        "utcdatetime",
        "utcoffset",
        "utctime",
        "write",
        "writebytes",
        "writefile",
        "writeln",
    }
)

_BUILTIN_DISPLAY_SEGMENTS: tuple[tuple[str, str], ...] = (
    ("abs", "Abs"),
    ("add", "Add"),
    ("append", "Append"),
    ("appendbytes", "AppendBytes"),
    ("appendfile", "AppendFile"),
    ("array", "Array"),
    ("contains", "Contains"),
    ("all", "All"),
    ("count", "Count"),
    ("initialize", "Initialize"),
    ("clear", "Clear"),
    ("clone", "Clone"),
    ("insert", "Insert"),
    ("indexof", "IndexOf"),
    ("lastindexof", "LastIndexOf"),
    ("asc", "Asc"),
    ("ascii", "ASCII"),
    ("ascw", "AscW"),
    ("base64", "Base64"),
    ("binary", "Binary"),
    ("binarylength", "BinaryLength"),
    ("binarymid", "BinaryMid"),
    ("binarytostring", "BinaryToString"),
    ("bit", "Bit"),
    ("bitand", "BitAnd"),
    ("bitnot", "BitNot"),
    ("bitnotunsigned", "BitNotUnsigned"),
    ("bitor", "BitOr"),
    ("bitrotate", "BitRotate"),
    ("bitshift", "BitShift"),
    ("bitxor", "BitXor"),
    ("box", "Box"),
    ("bytes", "Bytes"),
    ("ceiling", "Ceiling"),
    ("chr", "Chr"),
    ("chrw", "ChrW"),
    ("color", "Color"),
    ("combine", "Combine"),
    ("compare", "Compare"),
    ("copy", "Copy"),
    ("copydir", "CopyDir"),
    ("copyfile", "CopyFile"),
    ("converttimezone", "ConvertTimeZone"),
    ("movedir", "MoveDir"),
    ("movefile", "MoveFile"),
    ("create", "Create"),
    ("createdir", "CreateDir"),
    ("current", "Current"),
    ("diag", "Diag"),
    ("date", "Date"),
    ("dateadd", "DateAdd"),
    ("datediff", "DateDiff"),
    ("datepart", "DatePart"),
    ("dateserial", "DateSerial"),
    ("datetolocalstring", "DateToLocalString"),
    ("datetostring", "DateToString"),
    ("datetoutcstring", "DateToUTCString"),
    ("dayofweek", "DayOfWeek"),
    ("dayofyear", "DayOfYear"),
    ("daysinmonth", "DaysInMonth"),
    ("delay", "Delay"),
    ("delete", "Delete"),
    ("deletefile", "DeleteFile"),
    ("directorydelete", "DirectoryDelete"),
    ("diff", "Diff"),
    ("digit", "Digit"),
    ("dir", "Dir"),
    ("directoryname", "DirectoryName"),
    ("directory", "Directory"),
    ("direxists", "DirExists"),
    ("remove", "Remove"),
    ("down", "Down"),
    ("endofday", "EndOfDay"),
    ("endofmonth", "EndOfMonth"),
    ("event", "Event"),
    ("exists", "Exists"),
    ("exp", "Exp"),
    ("extensionname", "ExtensionName"),
    ("file", "File"),
    ("fileexists", "FileExists"),
    ("filechecksum", "FileChecksum"),
    ("filecompare", "FileCompare"),
    ("fileinfo", "FileInfo"),
    ("filehash", "FileHash"),
    ("enumerate", "Enumerate"),
    ("enumeratefiles", "EnumerateFiles"),
    ("list", "List"),
    ("float", "Float"),
    ("floor", "Floor"),
    ("format", "Format"),
    ("formatdatetime", "FormatDateTime"),
    ("formatdatetimeinoffset", "FormatDateTimeInOffset"),
    ("from", "From"),
    ("frombase64", "FromBase64"),
    ("fromhex", "FromHex"),
    ("get", "Get"),
    ("getclassname", "GetClassName"),
    ("getclientrect", "GetClientRect"),
    ("getcurrenteventdelay", "GetCurrentEventDelay"),
    ("getcursorpos", "GetCursorPos"),
    ("getmonitorinfo", "GetMonitorInfo"),
    ("getmonitorinfoex", "GetMonitorInfoEx"),
    ("getmousemovespeed", "GetMouseMoveSpeed"),
    ("getparent", "GetParent"),
    ("getwindowlongptr", "GetWindowLongPtr"),
    ("getwindowplacement", "GetWindowPlacement"),
    ("getwindowrect", "GetWindowRect"),
    ("getwindowtext", "GetWindowText"),
    ("hex", "Hex"),
    ("hotkey", "HotKey"),
    ("int", "Int"),
    ("info", "Info"),
    ("hash", "Hash"),
    ("is", "Is"),
    ("isdate", "IsDate"),
    ("isiconic", "IsIconic"),
    ("isleapyear", "IsLeapYear"),
    ("ispathvalid", "IsPathValid"),
    ("istime", "IsTime"),
    ("iswindowenabled", "IsWindowEnabled"),
    ("iswindowvisible", "IsWindowVisible"),
    ("iszoomed", "IsZoomed"),
    ("key", "Key"),
    ("keydown", "KeyDown"),
    ("keypress", "KeyPress"),
    ("keys", "Keys"),
    ("keytoggle", "KeyToggle"),
    ("keyup", "KeyUp"),
    ("length", "Length"),
    ("ln", "Ln"),
    ("local", "Local"),
    ("lower", "Lower"),
    ("mid", "Mid"),
    ("mod", "Mod"),
    ("mouseclick", "MouseClick"),
    ("mouseclickdrag", "MouseClickDrag"),
    ("mousedown", "MouseDown"),
    ("mousedrag", "MouseDrag"),
    ("mousemove", "MouseMove"),
    ("mouseup", "MouseUp"),
    ("mousewheel", "MouseWheel"),
    ("move", "Move"),
    ("match", "Match"),
    ("msg", "Msg"),
    ("msgbox", "MsgBox"),
    ("name", "Name"),
    ("normalize", "Normalize"),
    ("not", "Not"),
    ("nowdate", "NowDate"),
    ("nowdatetime", "NowDateTime"),
    ("nowtime", "NowTime"),
    ("parse", "Parse"),
    ("parsedatetimeinoffset", "ParseDateTimeInOffset"),
    ("path", "Path"),
    ("pathcombine", "PathCombine"),
    ("pathexists", "PathExists"),
    ("pathnormalize", "PathNormalize"),
    ("pixel", "Pixel"),
    ("pixelgetcolor", "PixelGetColor"),
    ("pixelsearch", "PixelSearch"),
    ("pop", "Pop"),
    ("read", "Read"),
    ("readbytes", "ReadBytes"),
    ("readfile", "ReadFile"),
    ("replace", "Replace"),
    ("ends", "Ends"),
    ("enumeratefiles", "EnumerateFiles"),
    ("join", "Join"),
    ("regex", "Regex"),
    ("reverse", "Reverse"),
    ("round", "Round"),
    ("search", "Search"),
    ("size", "Size"),
    ("walk", "Walk"),
    ("walkdir", "WalkDir"),
    ("send", "Send"),
    ("sendkeys", "SendKeys"),
    ("sendtext", "SendText"),
    ("set", "Set"),
    ("setcurrenteventdelay", "SetCurrentEventDelay"),
    ("setmousemovespeed", "SetMouseMoveSpeed"),
    ("sleep", "Sleep"),
    ("space", "Space"),
    ("speed", "Speed"),
    ("sort", "Sort"),
    ("slice", "Slice"),
    ("unique", "Unique"),
    ("split", "Split"),
    ("startofday", "StartOfDay"),
    ("startofmonth", "StartOfMonth"),
    ("startofweek", "StartOfWeek"),
    ("starts", "Starts"),
    ("string", "String"),
    ("stringinstr", "StringInStr"),
    ("stringisalpha", "StringIsAlpha"),
    ("stringisalphanumeric", "StringIsAlphaNumeric"),
    ("stringisascii", "StringIsASCII"),
    ("stringisdigit", "StringIsDigit"),
    ("stringisfloat", "StringIsFloat"),
    ("stringisint", "StringIsInt"),
    ("stringislower", "StringIsLower"),
    ("stringisspace", "StringIsSpace"),
    ("stringisupper", "StringIsUpper"),
    ("stringleft", "StringLeft"),
    ("push", "Push"),
    ("stringlength", "StringLength"),
    ("stringmid", "StringMid"),
    ("stringreplace", "StringReplace"),
    ("stringreverse", "StringReverse"),
    ("stringright", "StringRight"),
    ("stringtolower", "StringToLower"),
    ("stringtoupper", "StringToUpper"),
    ("stringtrimleft", "StringTrimLeft"),
    ("stringtrimright", "StringTrimRight"),
    ("with", "With"),
    ("text", "Text"),
    ("time", "Time"),
    ("timeserial", "TimeSerial"),
    ("timezoneoffset", "TimeZoneOffset"),
    ("to", "To"),
    ("toggle", "Toggle"),
    ("up", "Up"),
    ("upper", "Upper"),
    ("utc", "UTC"),
    ("utcdatetime", "UTCDateTime"),
    ("utcoffset", "UTCOffset"),
    ("utctime", "UTCTime"),
    ("valid", "Valid"),
    ("wheel", "Wheel"),
    ("write", "Write"),
    ("writebytes", "WriteBytes"),
    ("writefile", "WriteFile"),
)
_BUILTIN_DISPLAY_SEGMENT_MAP = dict(_BUILTIN_DISPLAY_SEGMENTS)
_BUILTIN_DISPLAY_SEGMENT_NAMES = sorted(_BUILTIN_DISPLAY_SEGMENT_MAP, key=len, reverse=True)


def format_builtin_function_name(name: str) -> str:
    normalized = str(name).strip().lower()
    if not normalized:
        return str(name)

    remaining = normalized
    parts: list[str] = []
    while remaining:
        matched_segment = None
        for segment in _BUILTIN_DISPLAY_SEGMENT_NAMES:
            if remaining.startswith(segment):
                matched_segment = segment
                break
        if matched_segment is None:
            return str(name[:1]).upper() + str(name[1:])
        parts.append(_BUILTIN_DISPLAY_SEGMENT_MAP[matched_segment])
        remaining = remaining[len(matched_segment):]

    return "".join(parts) if parts else str(name).capitalize()


def is_builtin_function(name: str) -> bool:
    return str(name).strip().lower() in BUILTIN_FUNCTION_NAMES
